const products=[
 {id:1,name:'Green Garden Bowl',category:'lunch vegetarian',desc:'Seasonal greens, grains and a bright herb dressing.',price:'—',tag:'Vegetarian',image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=700&q=80'},
 {id:2,name:'Sunrise Egg Plate',category:'breakfast',desc:'A wholesome start made with fresh, simple ingredients.',price:'—',tag:'Breakfast',image:'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=700&q=80'},
 {id:3,name:'Tiffin Comfort Bowl',category:'lunch dinner',desc:'A satisfying, home-style meal for busy days.',price:'—',tag:'Chef’s pick',image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=700&q=80'},
 {id:4,name:'Fresh Crunch Salad',category:'lunch vegetarian',desc:'Crisp vegetables and thoughtful textures in every bite.',price:'—',tag:'Fresh',image:'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=700&q=80'}
];
let cart=[];
const grid=document.querySelector('#product-grid');
function renderProducts(filter='all'){const shown=filter==='all'?products:products.filter(p=>p.category.includes(filter));grid.innerHTML=shown.map(p=>`<article class="product-card"><span class="tag">${p.tag}</span><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="product-meta"><span class="price">${p.price==='—'?'Price to be announced':'PKR '+p.price}</span><button class="add-button" data-add="${p.id}" aria-label="Add ${p.name} to cart">+</button></div></div></article>`).join('');document.querySelector('.empty-state').hidden=shown.length>0;}
renderProducts();
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderProducts(btn.dataset.filter)}));
grid.addEventListener('click',e=>{const btn=e.target.closest('[data-add]');if(!btn)return;const product=products.find(p=>p.id===Number(btn.dataset.add));if(product.price==='—'){alert('This product is coming soon. Prices will be added once finalized.');return}cart.push(product);updateCart();openCart()});
function updateCart(){document.querySelector('.cart-count').textContent=cart.length;const box=document.querySelector('.cart-items');box.innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-item"><img src="${p.image}" alt=""><div><h4>${p.name}</h4><p>PKR ${p.price}</p><button data-remove="${i}">Remove</button></div></div>`).join(''):'<p class="empty-cart">Your cart is waiting for something delicious.</p>';document.querySelector('#cart-total').textContent=cart.reduce((sum,p)=>sum+Number(p.price),0).toLocaleString();}
document.querySelector('.cart-items').addEventListener('click',e=>{if(e.target.dataset.remove!==undefined){cart.splice(Number(e.target.dataset.remove),1);updateCart()}});
const drawer=document.querySelector('.cart-drawer'),overlay=document.querySelector('.overlay');function openCart(){drawer.classList.add('open');overlay.classList.add('open');drawer.setAttribute('aria-hidden','false')}function closeCart(){drawer.classList.remove('open');overlay.classList.remove('open');drawer.setAttribute('aria-hidden','true')}document.querySelector('[data-open-cart]').addEventListener('click',openCart);document.querySelectorAll('[data-close-cart]').forEach(el=>el.addEventListener('click',closeCart));
const toggle=document.querySelector('.menu-toggle');toggle.addEventListener('click',()=>{const nav=document.querySelector('.nav');nav.classList.toggle('open');toggle.setAttribute('aria-expanded',nav.classList.contains('open'))});document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>document.querySelector('.nav').classList.remove('open')));
document.querySelector('.signup-form').addEventListener('submit',e=>{e.preventDefault();e.target.querySelector('.form-message').textContent='Thanks — we’ll keep you posted.';e.target.reset()});document.querySelector('.checkout-button').addEventListener('click',()=>alert('Checkout will be enabled once pricing and payment details are finalized.'));
